### ISSUE TITLE
Do your sorting functions have side effects?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [1fabiopereira/node-sortable#3]
I am interested in your library, but before using it I would like to know if the sorting functions are pure, of if they have side effects.

For example, the normal `Array.prototype.sort` is not a pure function and has side effects as it changes the array it receives directly. A pure function, would instead return a new array, ordered without affecting the first one.

**Comment by Fl4m3Ph03n1x** [comment]
After testing the code I can confirm that this function has side effects. Not only does it return a new array, it also changes the array that is passed as a parameter. This is quite confusing.

If you are returning an array, I expect that the data I first give you should not be modified and thus I assume the function is pure.

On the other hand, if you modify the object I pass as a parameter, I expect it to not return anything.

I also tested the heap sort with the following code, and it failed:

```
const input = [ { id: 8, score: 60, partnerId: 23 },
  { id: 7, score: 55, partnerId: 23 },
  { id: 6, score: 65, partnerId: 23 },
  { id: 5, score: 50, partnerId: 23 },
  { id: 4, score: 40, partnerId: 23 },
  { id: 3, score: 30, partnerId: 23 },
  { id: 2, score: 20, partnerId: 23 } ];

  const orderedArray = heap( input, ( obj1, obj2 ) => obj1.score < obj2.score );
  console.log(orderedArray);

This code output is:

[ { id: 8, score: 60, partnerId: 23 },
  { id: 2, score: 20, partnerId: 23 },
  { id: 3, score: 30, partnerId: 23 },
  { id: 4, score: 40, partnerId: 23 },
  { id: 5, score: 50, partnerId: 23 },
  { id: 6, score: 65, partnerId: 23 },
  { id: 7, score: 55, partnerId: 23 } ]
```

The orderedArray should be ordered by score, but such is not the case.

**Comment by 1fabiopereira** [comment]
@Fl4m3Ph03n1x  I will check how I can solve these problems that you raised and as soon as possible I give you an answer.

**Comment by 1fabiopereira** [comment]
@Fl4m3Ph03n1x  I will check how I can solve these problems that you raised and as soon as possible I give you an answer.

**Comment by 1fabiopereira** [comment]
@Fl4m3Ph03n1x  I will check how I can solve these problems that you raised and as soon as possible I give you an answer.

**Comment by 1fabiopereira** [comment]
@Fl4m3Ph03n1x  Currently the Heapsort implementation only supports numbers, but as I said earlier I will work to correct these problems.

**Comment by Fl4m3Ph03n1x** [comment]
> Currently the Heapsort implementation only supports numbers

In the documentation you do have an example of heapsort ordering objects via age :p

Perhaps I could be of assistance ?
I am of the opinion the documentation could use some help, and I know how to resolve some of the issues I pointed. However  when I checked the *How to contribute page* it was empty !

So I am not sure at all if you are accepting pull requests or not. 

For me the perfect solution would be to have an API that people expect. For example, when sorting something, one could pass a compare function, like the one used here:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

I defend this would be a good idea because it would be usable by your algorithms and people would be used to it ( it would follow the principle of least astonishment ).

**Comment by 1fabiopereira** [comment]
Dear all help is welcome, I am thinking of doing a refactoring in this lib, we can agree along the standard for contribution if you want.

**Comment by Fl4m3Ph03n1x** [comment]
It would be my pleasure to endorse in a new venture with a (I assume) fellow Portuguese speaker 🥇 
You can check some of my NPM libraries to see how I code and how I organize things: 

 - https://www.npmjs.com/~fl4m3ph03n1x

Some people may think I am a badge fanatic, but I think the point of badges is to transmit an important message: my work has quality you can trust. 

And I believe we all want the same :D

Do you want to have a meeting? I may be free during the weekend. I think it would be beneficial, at least for me, since I would like to know how you plan on refactoring your code so I could give an opinion.

**Comment by 1fabiopereira** [comment]
so let's create the channel in the slack and we will discuss the improvements that can be adopted

**Comment by Fl4m3Ph03n1x** [comment]
Here is an invite link:

https://join.slack.com/t/node-sortable/shared_invite/enQtMjcwMTAxMjU5MTI1LTE2YzBlN2I1ODA1Y2JmNzgzMjZjZTA2MWViNDAwZDAwMmE5NWMxNzhiZWI0ODFiYzZiMDhlOTZiNzQzYmJhN2Y

Let me know once you have joined, so I can edit this post !

**Comment by Fl4m3Ph03n1x** [comment]
Working on 2.0
